host_uri: rosettastoneqadev.adobeconnect.com
proxy_host: http://dalproxy.lan.flt:3128
username: adobeconnectws-qadev-gg@rosettastone.com
password: 5@538^0LN242(3n
user_password: y{Mf;fK%{Ru4#3>
meeting_folder_id: 1276256662
template_id: 1276158945
