url: bbb.dev.rosettastone.com
proxy_host: http://dalproxy.lan.flt:3128
salt: e4d91adbc729a0aa4b9d84029fef20f2
attendeePW: attendeePW
moderatorPW: moderatorPW
name: Live Session
record: true
CLIENT_ID: Client.CSP
CLIENT_PASSWORD: xn688R8622vCP2n7gJ45Yz1b7
username: csp@rosettastone.com
password: xn688R8622vCP2n7gJ45Yz1b7
host_url: scholar-dev.dev.rosettastone.com
